### ISSUE TITLE
Ломает json ответы AJAX

### ISSUE THREAD

**Issue by rogodessa** [seojacky/helper-lite-for-pagespeed#10]
Приветствую.

При фильтрации буфера, под раздачу попадает все, в том числе и AJAX. Если в ответе есть тег img, то после фильтра подставляются decoding="async" loading="lazy" без экранирования кавычек.

Скрин: http://dl3.joxi.net/drive/2020/07/18/0022/3684/1474148/48/215c022397.jpg

**Comment by bounia** [comment]
должно быть пофикшено в 2.5.3, добавлено условие "if( wp_doing_ajax() )", при котором кавычки экранируются. К сожалению, у меня сейчас нет возможности проверить этот момент на реальном примере, так что оставляю тему открытой до появления отзывов.
