### ISSUE TITLE
Для будущей 2.6

### ISSUE THREAD

**Issue by seojacky** [seojacky/helper-lite-for-pagespeed#3]
один момент, этот вариант фильтрует вообще ВЕСЬ аутпут, даже админки
так что если у кого-то такой плагин будет крашить сайт, он положит и админку тоже
стоит каким-то образом прописать чтобы данный фильтр не выполнялся для админа, чтобы плагин можно было отключить

**Comment by mihdan** [comment]
```
if ( is_admin() ) {
    return;
}
```
