### ISSUE TITLE
начинает конфликтовать с контакт форм 7

### ISSUE THREAD

**Issue by seojacky** [seojacky/helper-lite-for-pagespeed#9]
если поставить галочку Events with attribute passive perform better for touch and wheel то начинает конфликтовать с контакт форм 7, ложное уведомление срабатывает Ошибка при отправке сообщения. Попытайтесь позже или обратитесь к администратору сайта. Хотя письмо на почту попадает

**Comment by bounia** [comment]
должно быть пофикшено в 2.5.3, теперь атрибут passive добавляется только к событиям "touchstart", "scroll" и "wheel", так что с событиями кф7 конфликтовать не должно. Пока что оставляют тему открытой, так как на реальном примере не проверялось.
